# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UBER-CLONE-UIKIT-TRAINING' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UBER-CLONE-UIKIT-TRAINING

  pod 'GeoFire', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

end
